### ISSUE TITLE
Not fit for some devices

### ISSUE THREAD

**Issue by rebelholic** [AlexDisler/ng-special-offer#2]
Hello,

I've got problem with your plugin after tested on my phone device such as Motorola Moto G not show the agree button unless tested on my android tablet show all buttons. You can check my screenshot below:
![screenshot_2015-03-28-14-55-33](https://cloud.githubusercontent.com/assets/6254876/7104533/18475e68-e112-11e4-9e39-0f07cc87fec3.png)

Could you fix it with soon?

**Comment by AlexDisler** [comment]
Hi,

Some Android devices seem to only display 2 buttons for the native dialogs (using cordova-plugin-dialogs).

I've changed the order of the buttons so that the first button will approve, second button will decline and third button will be the "remind me later" button. This way if the dialog only displays two buttons, it will still be functional.
https://github.com/AlexDisler/ng-special-offer/commit/60d48e050847345c19e09ea1a45a96209f038fdf

Hope this helps.
